name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
      - '*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        name: 'Qodana Scan'
        with:
          pr-mode: false
          fetch-depth: 0 # a full history is required for pull request analysis
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        name: 'Qodana Scan PR'
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
          pr-mode: false
      - name: 'Qodana Scan Action'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
